### ISSUE TITLE
Doesn't seem to be working in Xcode 6.2

### ISSUE THREAD

**Issue by kvnify** [molon/MLAutoReplace#2]
I have this plugin installed via Alcatraz and yet it doesn't appear to be doing anything. I can not see any menu options for editing the plist. The auto indent is also not functional.

**Comment by iNono22** [comment]
Same for me :(

**Comment by molon** [comment]
@khendry  @arnaudWasappli   thanks for using.  [see commit](https://github.com/molon/MLAutoReplace/commit/21beea4886a8e779fffd20691b7c5b96f57664e9)
