### ISSUE TITLE
How to use auto getter generator

### ISSUE THREAD

**Issue by ruozi** [molon/MLAutoReplace#4]
I've installed this plugin and confirm that getter plist exits.

Also I reload .plist data before I use it,but when I write getters, it seems doesn't work.

**Comment by molon** [comment]
![image](https://cloud.githubusercontent.com/assets/3739161/9582282/04976de2-5037-11e5-9740-5361ec554bcb.png)
are the default getters useable? @ruozi 
maybe you need give more clear information for your custom getter.

**Comment by ruozi** [comment]
No，I can't use default getters (UILabel, UIImage).

But I can see MLAutoReplace option in my XCode->Window

**Comment by molon** [comment]
@ruozi it's so strange.
and what's your XCode version?

is auto re-intent useable?

**Comment by ruozi** [comment]
My Xcode version is 6.4

And when I use auto-indent, I can see the checkall operation but auto-indent not work

**Comment by molon** [comment]
@ruozi my xcode version is 6.4 too. ——！
using getter replacer example:

```
- (UIButton*)button///
```

`///` is important. maybe it's not clear in readme.

`@s/` is useable? 

if auto-retent can checkall, the plugin must be installed successfully.

**Comment by ruozi** [comment]
OK, I don't use `\\\`  lol, Thx very much!

**Comment by molon** [comment]
@ruozi  OK。 :)
