### ISSUE TITLE
make no effect

### ISSUE THREAD

**Issue by oit63** [molon/MLAutoReplace#6]
I installed MLAutoReplace,
but it makes no sense.
I am sure the key-binding is default as C-I.

**Comment by molon** [comment]
is `@s/` valid?
and what's your Xcode version?

**Comment by molon** [comment]
@ForrestAlfred I have tested install with Alcatraz just now.
We need restart Xcode and enable load the plugin.

If install with Alcatraz is not useful.
maybe you can test to build and run it in Xcode then restart.

**Comment by oit63** [comment]
I also installed Xvim, maybe something goes conflicted.

**Comment by oit63** [comment]
I am using Xcode 7.0

**Comment by molon** [comment]
@ForrestAlfred 
I installed Xvim for testing.
It's also ok in write mode of vim.
Maybe the auto-reintent will be grotesque.

But the regex command (eg`@s/`) works perfectly.
My Xcode is 7.0 too.

Now I also dont know what's happened.

![image](https://cloud.githubusercontent.com/assets/3739161/10075290/8a99f364-6307-11e5-833d-2bdbef8d032b.png)

does the menu display? If not, the plugin has not loaded.

**Comment by oit63** [comment]
Thanks,  following your instruction, I reload the intelli-Paste plugin. And find that some plugin is indeed not loaded. Then I reload Xcode, find this MLAutoReplace item appear on my Windows Menu.

@t and @s/ works well !
 perfect

**Comment by oit63** [comment]
Now MLAutoReplace works perfectly !

**Comment by molon** [comment]
No thanks, It's my pleasure. :)
