### ISSUE TITLE
MLAutoReplace 失效

### ISSUE THREAD

**Issue by oit63** [molon/MLAutoReplace#8]
我重新装了系统,  再把Xcode 装好以后再装 MLAutoReplace ,  就发现了：能匹配到 Regex, 但是不能输出预设的代码,  是 MLAutoReplace 需要什么依赖吗？ 7.0.1 和 7.1 都没法用了

**Comment by molon** [comment]
@ForrestAlfred 我这边也刚刚升级到了7.1  没有发现什么问题啊。 你是怎么装的，最好直接下载最新的代码直接Run。

**Comment by oit63** [comment]
我也不确定是什么原因,  也下载了最新代码,RUN 过,  但是确实不行, 可能是依赖没有配置好,  只能暂时先不用了

**Comment by molon** [comment]
@ForrestAlfred 其实并不需要任何依赖，最多可能会和其他插件冲突。 
嗯，如果以后发现了是什么引起的话，麻烦告知。:)

**Comment by oit63** [comment]
好的, 以后再试试看。 这次刚重装了电脑才失效的。

**Comment by molon** [comment]
@ForrestAlfred  :)
