### ISSUE TITLE
我找到失效的原因了

### ISSUE THREAD

**Issue by oit63** [molon/MLAutoReplace#9]
一次偶然的机会，我发现 MLAR 不起作用是输入法的原因：
我用的是自己制作布局的输入法，由 UKelele 制作。 键盘布局为 Workman

![workman](http://i.imgur.com/p9X8lPn.png)

但我不太清楚这是输入法或者是键盘布局哪一个造成的结果， 因为不明白 MLAR 的功能是如何实现的，是监听和发送键盘事件吗？

**Comment by molon** [comment]
@ForrestAlfred 是的，例如Auto Re-Indent功能是监听按键事件Shift+CMD+\ 然后程序模拟两次快捷键消息给XCode的source窗口，CMD+A->Control+I 。

**Comment by oit63** [comment]
下午装了个 ATProperty， 发现可以用，暂时先用了

**Comment by molon** [comment]
@ForrestAlfred OK 有问题再交流。

**Comment by oit63** [comment]
我搞明白产生影响的地方了. 我在做布局的时候把script 选成 Roman 就正常了. 之前是 Unicode.

**Comment by molon** [comment]
@ForrestAlfred 哈哈，其实我对键盘布局这块不是太懂。键盘按键响应是参考的VVDcoument。:)
